apiVersion: v1
kind: Secret
metadata:
  name: payments-svc-credentials
  namespace: payments-system
type: Opaque
stringData:
  username: payments-svc-user.rabbitmq.svc.cluster.local
  passwordHash: ""
