apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payments-svc-credentials-vault
  namespace: payments-system
spec:
  vaultAuthRef: rabbitmq/vault-auth-prod
  mount: secret
  path: rabbitmq/payments
  type: kv-v2
  destination:
    name: payments-svc-credentials
    create: true
